name: testplugin
description: Paper Test Plugin
version: '1.0-SNAPSHOT'
main: me.sativus.testplugin.Testplugin
api-version: '1.21'
commands:
  register:
    description: Register user to the server
    usage: /register <email> <password> <config_password>
  login:
    description: Login user to the server
    usage: /login <password>
  balance:
    description: Check your balance
    usage: /balance
  reload:
    description: Reload the plugin configuration
    usage: /reload
    permission: testplugin.reload
  freeze:
    description: Freeze time or weather in all worlds
    usage: /freeze <time|weather> <value>
    permission: testplugin.freeze
  unfreeze:
    description: Unfreeze time or weather in all worlds
    usage: /unfreeze <time|weather>
    permission: testplugin.unfreeze

permissions:
  testplugin.balance.get:
    description: Allows the user to get other players' balances
    default: op
  testplugin.balance.set:
    description: Allows the user to set other players' balances
    default: op
  testplugin.reload:
    description: Allows the user to reload the plugin configuration
    default: op
  testplugin.freeze:
    description: Allows the user to freeze time or weather
    default: op
  testplugin.unfreeze:
    description: Allows the user to unfreeze time or weather
    default: op
default-permission: false